### ISSUE TITLE
afterEach - Jasmine 2 and nesting problem

### ISSUE THREAD

**Issue by m1gu3l** [kensho/ng-describe#81] opened 2015-11-16 17:09 UTC
This is probably connected to #74 

```
ngDescribe({
	only: true,
	name: 'fail',
	tests: function(deps) {

		beforeEach(function() {
			console.log('before every');
		});

		describe('nested 1', function() {
			beforeEach(function() {
				console.log('before every 1');
			});

			it("1", function() {
				console.log("1");
			});

			it("1", function() {
				console.log("1");
			});

			afterEach(function() {
				console.log('after every 1');
			});
		});

		describe('nested 2', function() {
			beforeEach(function() {
				console.log('before every 2');
			});

			it("2", function() {
				console.log("2");
			});

			it("2", function() {
				console.log("2");
			});

			afterEach(function() {
				console.log('after every 2');
			});
		});

		afterEach(function() {
			console.log('after every');
		});

	}
});
```

should output:

- before every
  before every 1
  1
  after every 1
  after every

- before every
  before every 1
  1
  after every 1
  after every

- before every
  before every 2
  2
  after every 2
  after every

- before every
  before every 2
  2
  after every 2 
  after every

but outputs:

- before every
  before every 1
  1
  after every 1
  after every 2  :boom:
  after every

- before every
  before every 1
  1
  after every 1
  after every 2  :boom:
  after every

- before every
  before every 2
  2
  after every 1  :boom:
  after every 2
  after every

- before every
  before every 2
  2
  after every 1 :boom:
  after every 2
  after every

**Comment by bahmutov** [comment] 2015-11-16 17:41
yeah, they merged the pull request, but have not released a new version :(

**Comment by rhudea** [comment] 2015-11-27 16:00
This issue seems to be related to the previous revert afterEach hack. Reverting those changes seems to fix this issue with the latest version of jasmine.

The problem is that hack actually gather all afterEach function, even if they were in different "describe" blocks.

**Comment by bahmutov** [comment] 2015-12-03 15:41
ok, Jasmine 2.4.0 finally merged, so we can test it and remove our hacks!!! :fireworks: 

https://github.com/jasmine/jasmine/blob/master/release_notes/2.4.0.md

**Comment by bahmutov** [comment] 2016-02-22 19:43
It seems keeping the hacks to work around Jasmine's problems is not worth it. I have removed the tests and hacks, please use Mocha for example. https://github.com/kensho/ng-describe#note-to-jasmine-users

**Closed by bahmutov** 2016-02-22 19:43 UTC
